ERROR - 2023-01-01 05:32:49 --> Error connecting to the database: Error: Class "SQLite3" not found in C:\xampp\htdocs\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:74
Stack trace:
#0 C:\xampp\htdocs\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\SQLite3\Connection->connect(false)
#1 C:\xampp\htdocs\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php(48): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php(74): CodeIgniter\Database\SQLite3\Connection->initialize()
#3 C:\xampp\htdocs\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php(54): ExampleDatabaseTest->loadDependencies()
#4 C:\xampp\htdocs\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php(248): ExampleDatabaseTest->setUpDatabase()
#5 C:\xampp\htdocs\vendor\phpunit\phpunit\src\Framework\TestCase.php(1147): CodeIgniter\Test\CIUnitTestCase->setUp()
#6 C:\xampp\htdocs\vendor\phpunit\phpunit\src\Framework\TestResult.php(728): PHPUnit\Framework\TestCase->runBare()
#7 C:\xampp\htdocs\vendor\phpunit\phpunit\src\Framework\TestCase.php(904): PHPUnit\Framework\TestResult->run(Object(ExampleDatabaseTest))
#8 C:\xampp\htdocs\vendor\phpunit\phpunit\src\Framework\TestSuite.php(675): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#9 C:\xampp\htdocs\vendor\phpunit\phpunit\src\Framework\TestSuite.php(675): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#10 C:\xampp\htdocs\vendor\phpunit\phpunit\src\Framework\TestSuite.php(675): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#11 C:\xampp\htdocs\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(661): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#12 C:\xampp\htdocs\vendor\phpunit\phpunit\src\TextUI\Command.php(144): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\Framework\TestSuite), Array, Array, true)
#13 C:\xampp\htdocs\vendor\phpunit\phpunit\src\TextUI\Command.php(97): PHPUnit\TextUI\Command->run(Array, true)
#14 C:\xampp\htdocs\vendor\phpunit\phpunit\phpunit(98): PHPUnit\TextUI\Command::main()
#15 C:\xampp\htdocs\vendor\bin\phpunit(123): include('C:\\xampp\\htdocs...')
#16 {main}
ERROR - 2023-01-01 05:32:49 --> Error connecting to the database: Error: Class "SQLite3" not found in C:\xampp\htdocs\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php:74
Stack trace:
#0 C:\xampp\htdocs\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\SQLite3\Connection->connect(false)
#1 C:\xampp\htdocs\vendor\codeigniter4\framework\system\Database\SQLite3\Connection.php(48): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php(74): CodeIgniter\Database\SQLite3\Connection->initialize()
#3 C:\xampp\htdocs\vendor\codeigniter4\framework\system\Test\DatabaseTestTrait.php(54): ExampleDatabaseTest->loadDependencies()
#4 C:\xampp\htdocs\vendor\codeigniter4\framework\system\Test\CIUnitTestCase.php(248): ExampleDatabaseTest->setUpDatabase()
#5 C:\xampp\htdocs\vendor\phpunit\phpunit\src\Framework\TestCase.php(1147): CodeIgniter\Test\CIUnitTestCase->setUp()
#6 C:\xampp\htdocs\vendor\phpunit\phpunit\src\Framework\TestResult.php(728): PHPUnit\Framework\TestCase->runBare()
#7 C:\xampp\htdocs\vendor\phpunit\phpunit\src\Framework\TestCase.php(904): PHPUnit\Framework\TestResult->run(Object(ExampleDatabaseTest))
#8 C:\xampp\htdocs\vendor\phpunit\phpunit\src\Framework\TestSuite.php(675): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#9 C:\xampp\htdocs\vendor\phpunit\phpunit\src\Framework\TestSuite.php(675): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#10 C:\xampp\htdocs\vendor\phpunit\phpunit\src\Framework\TestSuite.php(675): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#11 C:\xampp\htdocs\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(661): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#12 C:\xampp\htdocs\vendor\phpunit\phpunit\src\TextUI\Command.php(144): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\Framework\TestSuite), Array, Array, true)
#13 C:\xampp\htdocs\vendor\phpunit\phpunit\src\TextUI\Command.php(97): PHPUnit\TextUI\Command->run(Array, true)
#14 C:\xampp\htdocs\vendor\phpunit\phpunit\phpunit(98): PHPUnit\TextUI\Command::main()
#15 C:\xampp\htdocs\vendor\bin\phpunit(123): include('C:\\xampp\\htdocs...')
#16 {main}
